### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by fifiteen82726** [lg/awardwiz#4]
https://awardwiz.com/

Error msg: 
```
Access to XMLHttpRequest at 'https://2so59loqz4.execute-api.us-east-1.amazonaws.com/main/browserless/function?key=awardAvailability-skiplagged-JFK-HND-2022-11-13' from origin 'https://awardwiz.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

![image](https://user-images.githubusercontent.com/6240395/182011358-3b87fadc-57e9-4263-b825-dae87322f702.png)

**Comment by fifiteen82726** [comment]
Looks good now

**Comment by lg** [comment]
yeah there's some rough blocking happening from some of the websites. i've been changing the browserless parameters and also adding a rolling proxy for requests, but this anti-bottling ML has been impressive. trying to focus on reliability. also not expecting others to use this readme-less project of mine, so don't be surprised if it cuts out here and there :)
